version: "3.8"
services:
  postgres-db:
    container_name: message-board
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mbproject
      POSTGRES_PASSWORD: password
      POSTGRES_DB: message-board
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5436:5432"

volumes:
  postgresql_data:
    driver: local