services:
  postgres-db:
    container_name: message-board
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: messageBoard
      POSTGRES_PASSWORD: password
      POSTGRES_DB: message-board
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5436:5432"